#----------------------------------------
#               OsTag
#           Contains ChatFormating and OsTag
#             By: IndianPL
#             for colors use &
#----------------------------
#       Placeholders
#
# <name> - player name [OsTag \ ChatFormater] \\name\\
# <ping> - player ping [OsTag \ ChatFormater]
# <health> - player health [OsTag \ ChatFormater]
# <max_health> - player max health [OsTag]
# <dimension> - player current dimension [ChatFormater]
# <xp> - player xp lvl [OsTag \ ChatFormater] //name//
# <gamemode> - player gamemode [OsTag]
# <msg> - player message [ChatFormater]
# <suffix> - player group sufix (Luck Perms Required) [OsTag \ ChatFormater] \\name\\
# <prefix> - player group prefix (Luck Perms Required) [OsTag \ ChatFormater] \\name\\
# <groupDisName> - player group dispalya mame (Luck Perms Required) [OsTag \ ChatFormater] \\name only\\
# <model> - device model [OsTag \ ChatFormater]
# <device> - player device [OsTag \ ChatFormater]
# <controler> - Player controls [OsTag ]
# <version> - Minecraft version [OsTag \ ChatFormater]
# <xuid> - get player xuid (DON'T WORKING WHEN PLAYER DONT XBOX ACCOUNT) [OsTag]
# <language> - player Language [OsTag \ ChatFormater]
# <cps> - left click per second counter [OsTag]
# <deathskull> - player skull info (DeathSkull plugin required) [OsTag \ ChatFormater] \\name\\
# <unique-description> - player unique description from config [OsTag \ ChatFormater] \\name\\
#if in the description of the placeholders any one contains \\name\\ it means that it can be used in the player's name in ostag
# for better work dont use \ , only use \n
#--------------------------
#       Modules
#
#OsTag module
OsTag: true
#
#ChatFormating module
ChatFormater: true
#
#when turn off some module restart server
#--------------------------
#     Important notes
#
#Note if you use only \ (BackSlash) in config, the plugin may produce errors in the console or not work
#
#
#if you use server-authoritative-movement=client-auth in powernukkitx, set this to false
PowerNukkiX-movement-server: true
#
#
#Score Tag (When true name don't change)
#May be buged when player is not new player (DON'T RELOAD SERVER OR PLUGIN ,when you change this restart server)
ScoreTagOnly: false
#--------------------------
#   OsTag options
#
#Information refresh time in seconds
refresh-time: 1
#
#
#Normal Player
nick: "<unique-description><xp> <groupDisName> <name> <suffix> "
subtag: "<device> | <controler> \n&eDevice Model: &r<model>\n&eGamemode: &r<gamemode>\n&eCps: &r<cps>  &ePing: <ping> &eXp: <xp> \n&eGame Version: &r<version> \n\n&eXuid: &r<xuid>\n\n&eLanguage: &r<language>\n<health>/<max_health>&c❤\n<deathskull>"
#
#
#Advanced Player
a-nick: "<unique-description><xp> <groupDisName> <name> <suffix> "
a-subtag: "<device> | <controler>\n&eCps: &r<cps>  &ePing: <ping>\n<health>/<max_health>&c❤\n&eXp: <xp>\n<deathskull>"
advanced-players:
  - "JndjanBartonka"
  - "TheTwuj"
#--------------------------
#    Formater options
#
#Message format
message-format: "<unique-description><dimension> &r<xp>&r <deathskull><groupDisName> <prefix> &r<name> <suffix> &r» <msg>"
#
#
#If this option set to true everyone can use & by default instead of §
and-for-all: true
#
#
#break between messages, why? so that the emotes you give players will be visible if they are 16x16 [exparimental]
break-between-messages:
  enable: true
#
#
#Censorship (remove all Upper words) [exparimental]
censorship:
  word: "Bread"
  enable: true
BlackWords:
  - "dupa"
  - "fuck"
  - "nab"
  - "ez"
  - "kutas"
#
#
#Cooldown [exparimental]
cooldown:
  enable: true
  delay: 10
  message: "&aYou must wait &b<left> &eSeconds&a!"
#--------------------------
#     Messages and informations
#
#When player don't have xbox live account loged show this information in <xuid> placeholder
guest: "&lGuest"
#Skull icon for DeathSkulls
Skull-icon: "&lSkull&r "
#Gamemodes
survival: "survival"
creative: "creative"
adventure: "adventure"
#Dimensions
overworld: "&aOverWorld&r"
nether: "&cNether&r"
end: "&eEnd&r"
#Ping colors
low-ping: "&a"
medium-ping: "&e"
high-ping: "&c"
#Xp colors (Why? use this as it is used on hive if you want)
1lvl: "&r"
10lvl: "&e"
15lvl: "&a"
20lvl: "&2"
25lvl: "&c"
30lvl: "&4"
#Players (here you can add a unique description or icon from your texture pack for a given player) [exparimental]
Players:
  default:
    description: " "
  JndjanBartonka:
    unique-description: " "
  RoXuSTheWolf:
    unique-description: " "
  nick-name-here1:
    unique-description: "icon from teksture or some text"
#Os
Windows: "&f[&bWindows&f]"
Android: "&f[&aAndroid&f]"
Ios: "&f[&bIos&f]"
Mac: "&f[&cMac Os&f]"
Fire: "&f[&6Fire Os&f]"
Gearvr: "&f[&aGearVr&f]"
Hololens: "&f[&aHoloLens&f]"
Dedicated: "&f[&aDedicated&f]"
TvOs: "&f[&aTvOs&f]"
PlayStation: "&f[&aPS&f]"
Nintendo: "&f[&aNintendo&f]"
Xbox: "&f[&aXbox&f]"
Unknow: "&f[&aUnknow&f]"
#Controls
touch: "Touch"
keyboard: "Keyboard"
gamepad: "GamePad"
motion_controller: "motion_controller"
UnknowControler: "Unknow"

#When you use indian emoji pack can use this emoijs
#Windows: ''
#Android: ''
#Ios: ''
#Mac: ''
#Fire: '&f[&6Fire Os&f]'
#Gearvr: '&f[&aGearVr&f]'
#Hololens: '&f[&aHoloLens&f]'
#Dedicated: '&f[&aDedicated&f]'
#TvOs: ''
#PlayStation: ''
#Nintendo: ''
#Xbox: ''
#Unknow: '&f[&aUnknow&f]'
#touch: Touch
#keyboard: Keyboard
#gamepad: GamePad
#motion_controller: motion_controller
#UnknowControler: Unknow

#--------------------------