#----------------------------------------
#               OsTag
#           Contains ChatFormating and OsTag
#             By: IndianPL
#             for colors use &
#           Discord: https://discord.com/invite/8fk27Jc9DF
#          Find more info on wiki: https://github.com/IndianBartonka/OsTag/wiki
#----------------------------
#       Placeholders
#
# Support PlaceholderAPI
#
# <name> - player name [OsTag | ChatFormater] \\name\\
# <ping> - player ping [OsTag | ChatFormater]
# <health> - player health [OsTag | ChatFormater]
# <max_health> - player max health [OsTag]
# <food> - player food [OsTag]
# <max_food> - player max food [OsTag]
# <dimension> - player current dimension [ChatFormater]
# <xp> - player xp lvl [OsTag | ChatFormater] //name//
# <gamemode> - player gamemode [OsTag]
# <msg> - player message [ChatFormater]
# <suffix> | %ostag_suffix% - player group sufix (Luck Perms Required) [OsTag | ChatFormater] \\name\\
# <prefix> | %ostag_prefix% - player group prefix (Luck Perms Required) [OsTag | ChatFormater] \\name\\
# <groupDisName> | %ostag_group% - player group dispalya mame (Luck Perms Required) [OsTag | ChatFormater] \\name only\\
# <model> - device model [OsTag | ChatFormater]
# <device> | %ostag_device% - player device [OsTag | ChatFormater]
# <controler> | %ostag_controler%  - Player controls [OsTag ]
# <version> | %ostag_version% - Player game version version [OsTag | ChatFormater]
# <xuid> - get player xuid [OsTag]
# <language> - player Language [OsTag | ChatFormater]
# <cps> | %ostag_cps% - left click per second counter [OsTag]
# <dimension> - get player dimension [ChatFormater]
# <unique-description> - player unique description from config [OsTag | ChatFormater] \\name\\
#if in the description of the placeholders any one contains \\name\\ it means that it can be used in the player's name in ostag
# for better work dont use | , only use \n
#placeholders with <> have a specific place of use but those with %% can be used everywhere and outside the plugin, of course if you have the placeholder api
#--------------------------
#       Modules
#
#OsTag module
OsTag: true
#
#ChatFormating module
ChatFormater: true
#
#when turn off some module restart server
#--------------------------
#     Important notes
#
#Note if you use only \ (BackSlash) in config, the plugin may produce errors in the console or not work
#
#
#if you use server-authoritative-movement=client-auth in powernukkitx, set this to false
movement-server: true
#
#
#--------------------------
#   OsTag options
#
#Choose what is should be displayed
ScoreTag: true
NameTag: true
#
#
#Information refresh time in seconds
refresh-time: 1
#
#
#Normal Player
nick: "%factions_faction% <unique-description><xp> <groupDisName> <name> <suffix> "
subtag: "%factions_faction% <device> | <controler> \n&eDevice Model: &r<model>\n&eGamemode: &r<gamemode>\n&eCps: &r<cps>  &ePing: <ping> &eXp: <xp> \n&eGame Version: &r<version> \n\n&eXuid: &r<xuid>\n\n&eLanguage: &r<language>\n<health>/<max_health>&c❤"
#
#
#Advanced Player
a-nick: "%factions_faction% <unique-description><xp> <groupDisName> <name> <suffix> "
a-subtag: "<food>/<max_food> \n%factions_faction% <device> | <controler>\n&eCps: &r<cps>  &ePing: <ping>\n<health>/<max_health>&c❤\n&eXp: <xp>\n&eGame Version: &r<version>"
advanced-players:
  - "ExamplePlayer"
#
#
#Disabled worlds [Experimental]
disabled-worlds:
  - "ExampleWorld"
#--------------------------
#    Formater options
#
#Message format
message-format: "%factions_faction% <prefix> &r<name> &r» <msg>"
#
#
#If this option set to true everyone can use & by default instead of §
and-for-all: false
#
#
#break between messages, why? so that the emotes you give players will be visible if they are 16x16 [exparimental]
break-between-messages:
  enable: false
#
#
#Censorship (remove all Upper words) [exparimental]
censorship:
  word: "Bread"
  enable: false
BlackWords:
  - "dupa"
  - "fuck"
  - "nab"
  - "ez"
  - "kutas"
#
#
#Cooldown [exparimental]
cooldown:
  enable: false
  delay: 10
  message: "&aYou must wait &b<left> &eSeconds&a!"
  over: "&aYou can chat now"
  bypass: "&aYou have immune to cooldown"
#--------------------------
#     Messages and informations
#
#When player don't have xbox live account loged show this information in <xuid> placeholder
guest: "&lGuest"
#Gamemodes
survival: "survival"
creative: "creative"
adventure: "adventure"
spectator: "spectator"
#Dimensions
overworld: "&aOverWorld&r"
nether: "&cNether&r"
end: "&eEnd&r"
#Ping colors
low-ping: "&a"
medium-ping: "&e"
high-ping: "&c"
#Xp colors (Why? use this as it is used on hive if you want)
1lvl: "&r"
10lvl: "&e"
15lvl: "&a"
20lvl: "&2"
25lvl: "&c"
30lvl: "&4"
#Players (here you can add a unique description or icon from your texture pack for a given player) [exparimental]
Players:
  default:
    description: " "
  JndjanBartonka:
    unique-description: " "
  RoXuSTheWolf:
    unique-description: " "
  nick-name-here1:
    unique-description: "icon from teksture or some text"
#Os
Windows: "&f[&bWindows&f]"
Android: "&f[&aAndroid&f]"
Ios: "&f[&bIos&f]"
Mac: "&f[&cMac Os&f]"
Fire: "&f[&6Fire Os&f]"
Hololens: "&f[&aHoloLens&f]"
Dedicated: "&f[&aDedicated&f]"
TvOs: "&f[&aTvOs&f]"
PlayStation: "&f[&aPS&f]"
Nintendo: "&f[&aNintendo&f]"
Xbox: "&f[&aXbox&f]"
Linux: "&f[&aLinux&f]"
Unknown: "&f[&aUnknown&f]"
#Controls
touch: "Touch"
keyboard: "Keyboard"
gamepad: "GamePad"
motion_controller: "motion_controller"
UnknownControler: "Unknown"

#When you use indian emoji pack can use this emoijs
#Windows: ''
#Android: ''
#Ios: ''
#Mac: ''
#Fire: '&f[&6Fire Os&f]'
#Hololens: '&f[&aHoloLens&f]'
#Dedicated: '&f[&aDedicated&f]'
#TvOs: ''
#PlayStation: ''
#Nintendo: ''
#Xbox: ''
#Linux: "&f[&aLinux&f]"
#Unknown: '&f[&aUnknown&f]'
#touch: Touch
#keyboard: Keyboard
#gamepad: GamePad
#motion_controller: motion_controller
#UnknownControler: Unknown

#--------------------------