#----------------------------------------
#               OsTag
#           Contains OsTag,ChatFormating and CpsLimiter
#             By: IndianPL
#             for colors use &
#           Discord: https://discord.com/invite/aXDs6qtDCV
#          Find more info on wiki: https://github.com/IndianBartonka/OsTag/wiki
#----------------------------
#       Placeholders
#
# Support PlaceholderAPI
#
# <name> - player name
# <dis_name> - player display name
# <ping> - player ping
# <health> - player health
# <max_health> - player max health
# <food> - player food
# <max_food> - player max food
# <dimension> - player current dimension
# <xp> | %ostag_xp%  - player xp lvl
# <gamemode> - player gamemode
# <msg> - player message [ChatFormater]
# <suffix> | %ostag_suffix% - player group suffix (Luck Perms Required)
# <preffix> | %ostag_preffix% - player group prefix (Luck Perms Required)
# <groupDisName> | %ostag_group% - player group display mame (Luck Perms Required)
# <model> - device model
# <device> | %ostag_device% - player device
# <controller> | %ostag_controller%  - Player controls
# <version> | %ostag_version% - Player game version version
# <xuid> - get player xuid
# <language> - player Language
# <cps> | %ostag_cps% - left click per second counter
# <unique_description> - player unique description from config
# <cooldown> | %ostag_cooldown% - chat cooldown seconds info
#Now you can use (almost) any placeholder anywhere you want (except <msg>)
#--------------------------
#       Modules
#
#If you don't want to remove the plugin but you don't want it to work enable this option
Disable: false
#
#UpDate checker on player join (only players with ostag.admin permission and must restart server to change this)
UpdateChecker: true
#
#Download the latest version automatically if possible
AutoUpdate: true
#
#OsTag module
OsTag: true
#
#ChatFormating module
ChatFormatter: true
#
#Cps limiter module
CpsLimiter: true
#
#
#when turn off some module restart server
#--------------------------
#     Important notes
#
#Note if you use only \ (BackSlash) in config, the plugin may produce errors in the console or not work
#
#
#if you use server-authoritative-movement=client-auth in powernukkitx, set this to false
Movement-server: true
#
#Public plugin debug
Debug: false
#
#If it is enabled, information about what a given player has done in forms is sent
FormsDebug: false
#
#--------------------------
#   OsTag options
#
#Choose what is should be displayed
ScoreTag: true
NameTag: true
#
#
#Information refresh time in ticks (20 ticks = 1 second)
refresh-time: 1
#
#
#Normal Player
nick: "%factions_faction% <unique_description><xp> <groupDisName> <dis_name> <suffix> <dimension> <version> "
subtag:
  - "%factions_faction% <device> | <controller> "
  - "&eGroup display name: <groupDisName>"
  - "&eDimension: <dimension>"
  - "&eDevice Model: &r<model> "
  - "&eGamemode: &r<gamemode>"
  - "&eCooldown: &r<cooldown> "
  - "&eCps: &r<cps>  &ePing: <ping> &eXp: <xp> "
  - "&eGame Version: &r<version> "
  - "&eXuid: &r<xuid>"
  - "&eLanguage: &r<language>"
  - "<health>/<max_health>&c❤"
#
#
#Advanced Player
a-nick: "%factions_faction% <unique_description><xp> <groupDisName> <dis_name> <suffix> <dimension> <version> "
a-subtag:
  - "%factions_faction% <device> | <controller>  "
  - "&eGroup display name: <groupDisName>"
  - "&eDimension: <dimension> "
  - "&eDevice Model: &r<model> "
  - "&eGamemode: &r<gamemode>"
  - "&eCooldown: &r<cooldown> "
  - "&eCps: &r<cps>  &ePing: <ping> &eXp: <xp> "
  - "&eGame Version: &r<version> "
  - "&eXuid: &r<xuid>"
  - "&eLanguage: &r<language>"
  - "<health>/<max_health>&c❤"
advanced-players:
  - "ExamplePlayer"
#
#
#Disabled worlds [Experimental]
disabled-worlds:
  - "ExampleWorld"
#--------------------------
#    Formater options
#
#Message format
message-format: "%factions_faction% <dimension> <cps> <food>/<max_food> <preffix> &r<name> &r» <msg> "
#
#
#If this option set to true everyone can use & by default instead of §
And-for-all: false
#
#
MentionSound: true
#
#
#Msg
Msg:
  enabled: true
  console-logs: true
  null-recipient: "&cCan't find &6<player>"
  you-disabled: "&cYou have disabled private messages!"
  has-disabled: "&&6<player> &chave disabled private messages!"
  to-player: "&7[&b<me>&4 ->&b &6<player>&7]&r "
  from-player: "&7[&6<player>&4 -> &b<me>&7]&r "
#
#
#break between messages, why? so that the emotes you give players will be visible if they are 16x16 [exparimental]
break-between-messages:
  enable: false
#
#
#Censorship (remove all Upper words) [exparimental]
censorship:
  word: '*'
  enable: false
BlackWords:
  - "dupa"
  - "fuck"
  - "nab"
  - "ez"
  - "kutas"
#
#
#Cooldown [exparimental]
cooldown:
  enable: false
  delay: 10
  message: "&aYou must wait &b<left> &eSeconds&a!"
  over: "&aYou can chat now"
  disabled: "&aCooldown now is disabled"
  bypass: "&aYou have immune to cooldown"
#--------------------------
#    CpsLimiter options
#
Cps:
  max: 10
  message: "&cTo fast! Your cps &b<cps> &cmax cps &b<maxCps>"
#
#--------------------------
#     Messages and informations
#
#When player don't have xbox live account loged show this information in <xuid> placeholder
guest: "&lGuest"
#Gamemodes
survival: "survival"
creative: "creative"
adventure: "adventure"
spectator: "spectator"
#Dimensions
overworld: "&aOverWorld&r"
nether: "&cNether&r"
end: "&eEnd&r"
#Ping colors
low-ping: "&a"
medium-ping: "&e"
high-ping: "&c"
#Xp colors (Why? use this as it is used on hive if you want)
1lvl: "&r"
5lvl: "&r6"
10lvl: "&e"
15lvl: "&a"
20lvl: "&2"
25lvl: "&c"
30lvl: "&4"
35lvl: "&d"
#Players (here you can add a unique description or icon from your texture pack for a given player) [exparimental]
Players:
  default:
    description: " "
  JndjanBartonka:
    unique-description: " "
  RoXuSTheWolf:
    unique-description: " "
  nick-name-here1:
    unique-description: "icon from teksture or some text"
#Os
Windows: "&f[&bWindows&f]"
Android: "&f[&aAndroid&f]"
Ios: "&f[&bIos&f]"
Mac: "&f[&cMac Os&f]"
Fire: "&f[&6Fire Os&f]"
Hololens: "&f[&aHoloLens&f]"
Dedicated: "&f[&aDedicated&f]"
TvOs: "&f[&aTvOs&f]"
PlayStation: "&f[&aPS&f]"
Nintendo: "&f[&aNintendo&f]"
Xbox: "&f[&aXbox&f]"
Linux: "&f[&aLinux&f]"
Unknown: "&f[&aUnknown&f]"
#Controls
Touch: "Touch"
Keyboard: "Keyboard"
Gamepad: "GamePad"
Motion_controller: "motion_controller"
UnknownController: "Unknown"

#When you use indian emoji pack can use this emoijs
#Windows: ''
#Android: ''
#Ios: ''
#Mac: ''
#Fire: '&f[&6Fire Os&f]'
#Hololens: '&f[&aHoloLens&f]'
#Dedicated: '&f[&aDedicated&f]'
#TvOs: ''
#PlayStation: ''
#Nintendo: ''
#Xbox: ''
#Linux: "&f[&aLinux&f]"
#Unknown: '&f[&aUnknown&f]'
#Touch: Touch
#Keyboard: Keyboard
#Gamepad: GamePad
#Motion_controller: motion_controller
#UnknownController: "Unknown"

#--------------------------
