main: me.indian.pl.OsTag
name: OsTag
author: IndianPL
description: OsTag plugin
version: '${project.version}'
api: [ "1.0.14" ]
commands:
  ostag:
    description: add/remove player to advanced player list
  tto:
    description: test command