main: me.indian.pl.OsTag
name: OsTag
author: IndianPL
description: OsTag plugin
version: 1.4.8
api: [ "1.0.14" ]
commands:
  ostag:
    description: add/remove player to advanced player list
  tto:
    description: test command
